### ISSUE TITLE
Feature Request: Start SDRTrunk-Monitor on Startup, and be able to start SDRTrunk on start of SDRTrunk-Monitor

### ISSUE THREAD

**Issue by cpg178-kcd** [LDZPLN1/SDRTrunk-Monitor#2]
Currently I run SDRTrunk on a server that is set to reboot once a day. This software would be perfect for my use case, but I currently launch SDRTrunk with a scheduled task after reboot direct from the batch file. I cant find a way to automatically start it from the Monitor application,,, Is this a feature that can be added?

**Comment by LDZPLN1** [comment]
Feature added. New checkbox in the Settings dialog to enable auto start.
